# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'numerical_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet(u"background:rgb(44, 49, 60);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame.setStyleSheet(u"QPushButton{\n"
                                 "\n"
                                 "background-color:black;\n"
                                 "color:white;\n"
                                 "}\n"
                                 "QPushButton:hover {\n"
                                 "background-color: rgb(57, 65, 80);\n"
                                 "	border: 2px solid rgb(61, 70, 86);\n"
                                 "}\n"
                                 "QPushButton:pressed {	\n"
                                 "	background-color: rgb(35, 40, 49);\n"
                                 "}	border: 2px solid rgb(43, 50, 61);\n"
                                 "\n"
                                 "background:trasparent;")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.tableWidget.setStyleSheet("            QTableWidget {\n"
                                       "background-color: #000000; \n"
                                       "alternate-background-color: #222222; \n"
                                       "gridline-color: #AAAAAA; \n"
                                       "color: #FFFFFF;\n"
                                       "selected-color: white;\n"
                                       "selection-background-color: #FFC000; \n"
                                       "selection-color: #AA00FF\n"
                                       "} \n"
                                       "           QTableWidget QHeaderView { background-color: #00000000;}\n"
                                       "QTableWidget QHeaderView::section { background-color: #444444; color: "
                                       "#FFFFFF; border: none; \n "
                                       "           Tborder-style: none;} \n"
                                       "           QTableWidget QHeaderView::section:checked { background-color: #FFC000; color: #000000;}\n"
                                       "           QHeaderView::section:horizontal { border-right: 1px solid #AAAAAA; }\n"
                                       "QHeaderView::section:vertical { border-bottom: 1px solid #AAAAAA; }\n "
                                       "QTableWidget QTableCornerButton::section {  background: #00000000;  border: "
                                       "0px   }")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.rows = QtWidgets.QComboBox(self.frame)
        self.rows.setObjectName("rows")
        self.rows.addItem("")
        self.rows.addItem("")
        self.rows.addItem("")
        self.rows.addItem("")
        self.rows.addItem("")
        self.rows.addItem("")

        self.rows.setStyleSheet(u"\n"
                                "\n"
                                "background-color:black;\n"
                                "color: white;\n"

                                )
        self.gridLayout.addWidget(self.rows, 0, 0, 1, 1)
        self.btn_Set = QtWidgets.QPushButton(self.frame)
        self.btn_Set.setObjectName("btn_Set")
        self.gridLayout.addWidget(self.btn_Set, 1, 0, 1, 3)

        self.btn_calc = QtWidgets.QPushButton(self.frame)
        self.btn_calc.setObjectName("btn_calc")
        self.gridLayout.addWidget(self.btn_calc, 0, 0, 0, 3)

        self.cloumns = QtWidgets.QComboBox(self.frame)
        self.cloumns.setObjectName("cloumns")
        self.cloumns.addItem("")
        self.cloumns.addItem("")
        self.cloumns.addItem("")
        self.cloumns.addItem("")
        self.cloumns.addItem("")

        self.gridLayout.addWidget(self.cloumns, 0, 2, 1, 1)
        self.cloumns.setStyleSheet(u"\n"
                                   "\n"
                                   "background-color:black;\n"
                                   "color:white;\n"
                                   "")
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", " X "))

        self.rows.setItemText(0, _translate("MainWindow", "2"))
        self.rows.setItemText(1, _translate("MainWindow", "3"))
        self.rows.setItemText(2, _translate("MainWindow", "4"))
        self.rows.setItemText(3, _translate("MainWindow", "5"))
        self.rows.setItemText(4, _translate("MainWindow", "6"))
        self.rows.setItemText(5, _translate("MainWindow", "7"))
        self.btn_Set.setText(_translate("MainWindow", "Set Matrix"))
        self.btn_calc.setText(_translate("MainWindow", "Calculate"))
        self.cloumns.setItemText(0, _translate("MainWindow", "3"))
        self.cloumns.setItemText(1, _translate("MainWindow", "4"))
        self.cloumns.setItemText(2, _translate("MainWindow", "5"))
        self.cloumns.setItemText(3, _translate("MainWindow", "6"))
        self.cloumns.setItemText(4, _translate("MainWindow", "7"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
